### ISSUE TITLE
min Chrome ver

### ISSUE THREAD

**Issue by raingart** [muzuiget/monkey-support#8]

**Comment by muzuiget** [comment]
Wildmonkey is derived from another extension of mine, [Dualsub](https://chromewebstore.google.com/detail/dualsub/gnlibmlfpencglodjpgnalbdebfhpmfp). It is to separate the custom style function of Dualsub into an independent extension. So some codes are shared with Dualsub.

In fact, I will only support the latest stable version of the browser, because Google will not let you downgrade the browser version for testing.

In theory, Chrome should not delete the installed extension, but not upgrade to the new version.
